### ISSUE TITLE
Build Fails 

### ISSUE THREAD

**Issue by luismeier** [ros-noetic-arch/ros-noetic-roslib#2]
I try to build this package with yay but unfortunately, it fails.

Here is the log:

```
:: (1/1) Parsing SRCINFO: ros-noetic-roslib
==> Making package: ros-noetic-roslib 1.15.8-1 (Di 18 Jan 2022 18:47:38)
==> Retrieving sources...
  -> Found ros-noetic-roslib-1.15.8.tar.gz
==> Validating source files with sha256sums...
    ros-noetic-roslib-1.15.8.tar.gz ... Passed
==> Making package: ros-noetic-roslib 1.15.8-1 (Di 18 Jan 2022 18:47:40)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found ros-noetic-roslib-1.15.8.tar.gz
==> Validating source files with sha256sums...
    ros-noetic-roslib-1.15.8.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting ros-noetic-roslib-1.15.8.tar.gz with bsdtar
==> Sources are ready.
==> Making package: ros-noetic-roslib 1.15.8-1 (Di 18 Jan 2022 18:47:44)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/luism/.cache/yay/ros-noetic-roslib/src/build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/noetic
-- This workspace overlays: /opt/ros/noetic
-- Found PythonInterp: /usr/bin/python (found suitable version "3.10.1", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using default Python package layout
-- Found PY_em: /usr/lib/python3.10/site-packages/em.py  
-- Using empy: /usr/lib/python3.10/site-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Skip enable_testing() when building binary package
-- Using CATKIN_TEST_RESULTS_DIR: /home/luism/.cache/yay/ros-noetic-roslib/src/build/test_results
-- Forcing gtest/gmock from source, though one was otherwise available.
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Found gmock sources under '/usr/src/gmock': gmock will be built
-- Found Python: /usr/bin/python3.10 (found version "3.10.1") found components: Interpreter 
-- Found Threads: TRUE  
-- Using Python nosetests: /usr/bin/nosetests-3.10
-- catkin 0.8.10
-- BUILD_SHARED_LIBS is on
-- Found Boost: /usr/lib64/cmake/Boost-1.78.0/BoostConfig.cmake (found version "1.78.0") found components: thread 
/opt/ros/noetic/share/catkin/cmake/interrogate_setup_dot_py.py:43: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.core
-- Installing devel-space wrapper /home/luism/.cache/yay/ros-noetic-roslib/src/ros-1.15.8/core/roslib/scripts/gendeps to /home/luism/.cache/yay/ros-noetic-roslib/src/build/devel/lib/roslib
-- Found Boost: /usr/lib64/cmake/Boost-1.78.0/BoostConfig.cmake (found version "1.78.0") found components: filesystem thread 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/luism/.cache/yay/ros-noetic-roslib/src/build
[ 50%] Building CXX object CMakeFiles/roslib.dir/src/package.cpp.o
[100%] Linking CXX shared library devel/lib/libroslib.so
[100%] Built target roslib
==> Entering fakeroot environment...
==> Starting package()...
Consolidate compiler generated dependencies of target roslib
[100%] Built target roslib
Install the project...
-- Install configuration: ""
-- Installing: /home/luism/.cache/yay/ros-noetic-roslib/pkg/ros-noetic-roslib/opt/ros/noetic/lib/pkgconfig/roslib.pc
-- Installing: /home/luism/.cache/yay/ros-noetic-roslib/pkg/ros-noetic-roslib/opt/ros/noetic/share/roslib/cmake/roslib-extras.cmake
-- Installing: /home/luism/.cache/yay/ros-noetic-roslib/pkg/ros-noetic-roslib/opt/ros/noetic/share/roslib/cmake/roslibConfig.cmake
-- Installing: /home/luism/.cache/yay/ros-noetic-roslib/pkg/ros-noetic-roslib/opt/ros/noetic/share/roslib/cmake/roslibConfig-version.cmake
-- Installing: /home/luism/.cache/yay/ros-noetic-roslib/pkg/ros-noetic-roslib/opt/ros/noetic/share/roslib/package.xml
+ cd /home/luism/.cache/yay/ros-noetic-roslib/src/ros-1.15.8/core/roslib
+ mkdir -p /home/luism/.cache/yay/ros-noetic-roslib/pkg/ros-noetic-roslib//opt/ros/noetic/lib/python3.10/site-packages
+ /usr/bin/env PYTHONPATH=/opt/ros/noetic/lib/python3.10/site-packages:/home/luism/.cache/yay/ros-noetic-roslib/src/build/lib/python3.10/site-packages:/opt/ros/noetic/lib/python3.10/site-packages CATKIN_BINARY_DIR=/home/luism/.cache/yay/ros-noetic-roslib/src/build /usr/bin/python /home/luism/.cache/yay/ros-noetic-roslib/src/ros-1.15.8/core/roslib/setup.py egg_info --egg-base /home/luism/.cache/yay/ros-noetic-roslib/src/build build --build-base /home/luism/.cache/yay/ros-noetic-roslib/src/build install --root=/home/luism/.cache/yay/ros-noetic-roslib/pkg/ros-noetic-roslib/ --prefix=/opt/ros/noetic --install-scripts=/opt/ros/noetic/bin
running egg_info
creating /home/luism/.cache/yay/ros-noetic-roslib/src/build/roslib.egg-info
writing /home/luism/.cache/yay/ros-noetic-roslib/src/build/roslib.egg-info/PKG-INFO
Traceback (most recent call last):
  File "/home/luism/.cache/yay/ros-noetic-roslib/src/ros-1.15.8/core/roslib/setup.py", line 10, in <module>
    setup(**d)
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 292, in run
    writer(self, ep.name, os.path.join(self.egg_info, ep.name))
  File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 656, in write_pkg_info
    metadata.write_pkg_info(cmd.egg_info)
  File "/usr/lib/python3.10/distutils/dist.py", line 1117, in write_pkg_info
    self.write_pkg_file(pkg_info)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 167, in write_pkg_file
    write_field('Summary', single_line(self.get_description()))
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 151, in single_line
    raise ValueError('Newlines are not allowed')
ValueError: Newlines are not allowed
CMake Error at catkin_generated/safe_execute_install.cmake:4 (message):
  
  execute_process(/home/luism/.cache/yay/ros-noetic-roslib/src/build/catkin_generated/python_distutils_install.sh)
  returned error code
Call Stack (most recent call first):
  cmake_install.cmake:65 (include)


make: *** [Makefile:100: install] Error 1
==> ERROR: A failure occurred in package().
    Aborting...
 -> error making: ros-noetic-roslib

```

Any help is apprecheated.

**Comment by acxz** [comment]
Sadly I am not able to reproduce this. The error believe is caused due to a specific version of `python-setuptools`. Can you make sure you are updated and try again?

**Comment by wznmickey** [comment]
I met this problem too. After upgrading setuptools to version 60.8.2 (from 59.1.1) through pip, it is solved.

**Comment by acxz** [comment]
I wonder if I have some python package that is causing a different codepath for installing packages, since I'm not able to reproduce.

**Comment by wznmickey** [comment]
自动回复：已收到，谢谢。

**Comment by acxz** [comment]
If anyone facing the issue can post their installed packages that would help me debug this. Running `pacman -Q > install_list.txt` and posting that file would in a comment would be just what I need.

**Comment by acxz** [comment]
Closing due to inactivity
